/**
 * Action Types
 */

export const GET_ALL_STATIONS_STATUS_IN_BOUNDARY_REQUEST = 'GET_ALL_STATIONS_STATUS_IN_BOUNDARY_REQUEST'
export const GET_ALL_STATIONS_STATUS_IN_BOUNDARY_SUCCESS = 'GET_ALL_STATIONS_STATUS_IN_BOUNDARY_SUCCESS'
export const GET_ALL_STATIONS_STATUS_IN_BOUNDARY_FAILURE = 'GET_ALL_STATIONS_STATUS_IN_BOUNDARY_FAILURE'

export const GET_STATION_INFORMATION_REQUEST = 'GET_STATION_INFORMATION_REQUEST'
export const GET_STATION_INFORMATION_SUCCESS = 'GET_STATION_INFORMATION_SUCCESS'
export const GET_STATION_INFORMATION_FAILURE = 'GET_STATION_INFORMATION_FAILURE'

export const HOVER_KEY_CHANGE = 'HOVER_KEY_CHANGE'